from toolbox.tree import BST, AVL

bst = BST()
# bst.insert(10)
# bst.insert(5)
# bst.insert(20)
# bst.insert(15)
# bst.insert(17)
# bst.insert(25)
# bst.insert(23)
# bst.insert(24)
# bst.insert(30)

# bst.insert(50)
# bst.insert(40)
# bst.insert(30)
# bst.insert(20)
# bst.insert(10)

bst.insert(10)
bst.insert(20)
bst.insert(30)
bst.insert(40)
bst.insert(50)

# bst.inorder(bst.root)
# print("\n")
# bst.level_order(bst.root)
# print(bst.height(bst.root))
# print(bst.min_node(bst.root).data)
# print(bst.root.data)
# bst.delete(bst.search(bst.root, 20))
# bst.delete(bst.root)
# print(bst.search(bst.root, 20))
# print(bst.search_parent(bst.root, 10))
# bst.level_order(bst.root)
# bst.inorder(bst.root)
# bst.delete(bst.root, 30)
# bst.level_order(bst.root)

avl = AVL()
avl.insert(avl.root, 10)
avl.insert(avl.root, 20)
avl.insert(avl.root, 24)
avl.insert(avl.root, 30)
avl.insert(avl.root, 22)
avl.insert(avl.root, 27)
avl.insert(avl.root, 33)
avl.inorder(avl.root)

